services:

  postgres_test:
    image: postgres:latest
    volumes:
      - test_data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - fd_test

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_test:5432/postgres"
      ASYNC_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres_test:5432/postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      CONTAINER_ENV: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres_test:
        condition: service_healthy
    networks:
      - fd_test

volumes:
  test_data:


networks:
  fd_test:
