"""new_revision

Revision ID: 852eb9186acc
Revises: 
Create Date: 2024-07-26 18:19:18.329148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852eb9186acc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('playset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playset_id'), 'playset', ['id'], unique=False)
    op.create_index(op.f('ix_playset_name'), 'playset', ['name'], unique=False)
    op.create_table('server',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('loader', sa.String(), nullable=False),
    sa.Column('game_version', sa.String(), nullable=False),
    sa.Column('builder', sa.String(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_id'), 'server', ['id'], unique=False)
    op.create_index(op.f('ix_server_name'), 'server', ['name'], unique=False)
    op.create_table('playsets_servers',
    sa.Column('playset_id', sa.String(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playset_id'], ['playset.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], )
    )
    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('allocated_memory', sa.Integer(), nullable=False),
    sa.Column('level_seed', sa.String(), nullable=False),
    sa.Column('motd', sa.String(), nullable=False),
    sa.Column('view_distance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('playsets_servers')
    op.drop_index(op.f('ix_server_name'), table_name='server')
    op.drop_index(op.f('ix_server_id'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_playset_name'), table_name='playset')
    op.drop_index(op.f('ix_playset_id'), table_name='playset')
    op.drop_table('playset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
