async def generate_properties(server):
    def format_boolean(setting):
        if setting:
            return "true"
        else:
            return "false"

    properties = (
        f"enable-jmx-monitoring={format_boolean(server.enable_jmx_monitoring)}\\n\\\n"
        + f"rcon.port={server.rcon_port}\\n\\\n"
        + f"level-seed={server.level_seed}\\n\\\n"
        + f"gamemode={server.gamemode}\\n\\\n"
        + f"enable-command-block={format_boolean(server.enable_command_block)}\\n\\\n"
        + f"enable-query={format_boolean(server.enable_query)}\\n\\\n"
        + f"enforce-secure-profile={format_boolean(server.enforce_secure_profile)}\\n\\\n"
        + f"level-name={server.level_name}\\n\\\n"
        + f"motd={server.motd}\\n\\\n"
        + f"query.port={server.query_port}\\n\\\n"
        + f"pvp={format_boolean(server.pvp)}\\n\\\n"
        + f"generate-structures={format_boolean(server.generate_structures)}\\n\\\n"
        + f"max-chained-neighbor-updates={server.max_chained_neighbor_updates}\\n\\\n"
        + f"difficulty={server.difficulty}\\n\\\n"
        + f"network-compression-threshold={server.network_compression_threshold}\\n\\\n"
        + f"max-tick-time={server.max_tick_time}\\n\\\n"
        + f"require-resource-pack={format_boolean(server.require_resource_pack)}\\n\\\n"
        + f"use-native-transport={format_boolean(server.use_native_transport)}\\n\\\n"
        + f"max-players={server.max_players}\\n\\\n"
        + f"online-mode={format_boolean(server.online_mode)}\\n\\\n"
        + f"enable-status={format_boolean(server.enable_status)}\\n\\\n"
        + f"allow-flight={server.allow_flight}\\n\\\n"
        + f"initial-disable-packs={server.initial_disabled_packs}\\n\\\n"
        + f"broadcast-rcon-to-ops={server.broadcast_rcon_to_ops}\\n\\\n"
        + f"view-distance={server.view_distance}\\n\\\n"
        + f"resource-pack-prompt={server.resource_pack_prompt}\\n\\\n"
        + f"allow-nether={format_boolean(server.allow_nether)}\\n\\\n"
        + f"enable-rcon={format_boolean(server.enable_rcon)}\\n\\\n"
        + f"sync-chunk-writes={format_boolean(server.sync_chunk_writes)}\\n\\\n"
        + f"op-permission-level={server.op_permission_level}\\n\\\n"
        + f"prevent-proxy-connections={format_boolean(server.prevent_proxy_connections)}\\n\\\n"
        + f"hide-online-players={format_boolean(server.hide_online_players)}\\n\\\n"
        + f"resource-pack={server.resource_pack}\\n\\\n"
        + f"entity-broadcast-range-percentage={server.entity_broadcast_range_percentage}\\n\\\n"
        + f"simulation-distance={server.simulation_distance}\\n\\\n"
        + f"rcon.password={server.rcon_password}\\n\\\n"
        + f"player-idle-timeout={server.player_idle_timeout}\\n\\\n"
        + f"force-gamemode={format_boolean(server.force_gamemode)}\\n\\\n"
        + f"rate-limit={server.rate_limit}\\n\\\n"
        + f"hardcore={format_boolean(server.hardcore)}\\n\\\n"
        + f"white-list={format_boolean(server.whitelisted)}\\n\\\n"
        + f"broadcast-console-to-ops={format_boolean(server.broadcast_console_to_ops)}\\n\\\n"
        + f"spawn-npcs={format_boolean(server.spawn_npcs)}\\n\\\n"
        + f"spawn-animals={format_boolean(server.spawn_animals)}\\n\\\n"
        + f"function-permission-level={server.function_permission_level}\\n\\\n"
        + f"text-filtering-config={server.text_filtering_config}\\n\\\n"
        + f"spawn-monsters={format_boolean(server.spawn_monsters)}\\n\\\n"
        + f"enforce-whitelist={format_boolean(server.enforce_whitelist)}\\n\\\n"
        + f"spawn-protection={server.spawn_protection}\\n\\\n"
        + f"resource-pack-sha1={server.resource_pack_sha1}\\n\\\n"
        + f"max-world-size={server.max_world_size}"
    )

    return properties
