async def generate_properties(settings):
    def format_boolean(setting):
        if setting:
            return "true"
        else:
            return "false"

    properties = (
        f"enable-jmx-monitoring={format_boolean(settings.enable_jmx_monitoring)}\\n\\\n"
        + f"rcon.port={settings.rcon_port}\\n\\\n"
        + f"level-seed={settings.level_seed}\\n\\\n"
        + f"gamemode={settings.gamemode}\\n\\\n"
        + f"enable-command-block={format_boolean(settings.enable_command_block)}\\n\\\n"
        + f"enable-query={format_boolean(settings.enable_query)}\\n\\\n"
        + f"enforce-secure-profile={format_boolean(settings.enforce_secure_profile)}\\n\\\n"
        + f"level-name={settings.level_name}\\n\\\n"
        + f"motd={settings.motd}\\n\\\n"
        + f"query.port={settings.query_port}\\n\\\n"
        + f"pvp={format_boolean(settings.pvp)}\\n\\\n"
        + f"generate-structures={format_boolean(settings.generate_structures)}\\n\\\n"
        + f"max-chained-neighbor-updates={settings.max_chained_neighbor_updates}\\n\\\n"
        + f"difficulty={settings.difficulty}\\n\\\n"
        + f"network-compression-threshold={settings.network_compression_threshold}\\n\\\n"
        + f"max-tick-time={settings.max_tick_time}\\n\\\n"
        + f"require-resource-pack={format_boolean(settings.require_resource_pack)}\\n\\\n"
        + f"use-native-transport={format_boolean(settings.use_native_transport)}\\n\\\n"
        + f"max-players={settings.max_players}\\n\\\n"
        + f"online-mode={format_boolean(settings.online_mode)}\\n\\\n"
        + f"enable-status={format_boolean(settings.enable_status)}\\n\\\n"
        + f"allow-flight={settings.allow_flight}\\n\\\n"
        + f"initial-disable-packs={settings.initial_disabled_packs}\\n\\\n"
        + f"broadcast-rcon-to-ops={settings.broadcast_rcon_to_ops}\\n\\\n"
        + f"view-distance={settings.view_distance}\\n\\\n"
        + f"resource-pack-prompt={settings.resource_pack_prompt}\\n\\\n"
        + f"allow-nether={format_boolean(settings.allow_nether)}\\n\\\n"
        + f"enable-rcon={format_boolean(settings.enable_rcon)}\\n\\\n"
        + f"sync-chunk-writes={format_boolean(settings.sync_chunk_writes)}\\n\\\n"
        + f"op-permission-level={settings.op_permission_level}\\n\\\n"
        + f"prevent-proxy-connections={format_boolean(settings.prevent_proxy_connections)}\\n\\\n"
        + f"hide-online-players={format_boolean(settings.hide_online_players)}\\n\\\n"
        + f"resource-pack={settings.resource_pack}\\n\\\n"
        + f"entity-broadcast-range-percentage={settings.entity_broadcast_range_percentage}\\n\\\n"
        + f"simulation-distance={settings.simulation_distance}\\n\\\n"
        + f"rcon.password={settings.rcon_password}\\n\\\n"
        + f"player-idle-timeout={settings.player_idle_timeout}\\n\\\n"
        + f"force-gamemode={format_boolean(settings.force_gamemode)}\\n\\\n"
        + f"rate-limit={settings.rate_limit}\\n\\\n"
        + f"hardcore={format_boolean(settings.hardcore)}\\n\\\n"
        + f"white-list={format_boolean(settings.whitelisted)}\\n\\\n"
        + f"broadcast-console-to-ops={format_boolean(settings.broadcast_console_to_ops)}\\n\\\n"
        + f"spawn-npcs={format_boolean(settings.spawn_npcs)}\\n\\\n"
        + f"spawn-animals={format_boolean(settings.spawn_animals)}\\n\\\n"
        + f"function-permission-level={settings.function_permission_level}\\n\\\n"
        + f"text-filtering-config={settings.text_filtering_config}\\n\\\n"
        + f"spawn-monsters={format_boolean(settings.spawn_monsters)}\\n\\\n"
        + f"enforce-whitelist={format_boolean(settings.enforce_whitelist)}\\n\\\n"
        + f"spawn-protection={settings.spawn_protection}\\n\\\n"
        + f"resource-pack-sha1={settings.resource_pack_sha1}\\n\\\n"
        + f"max-world-size={settings.max_world_size}"
    )

    return properties
